import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { barangays } from "../src/barangays";
import { footprintOf } from "../src/footprint";
import type { HazardCollection } from "../src/schema";
import { scenarios } from "../src/scenarios";

/**
 * What the model says about each barangay, precomputed.
 *
 * The hazard polygons already carry the barangay they fall in, so this is a
 * grouping rather than a spatial join: read each scenario, split its features
 * by barangay, and measure each group with the same footprintOf() the city
 * reading uses. One function, so a barangay's figure and the city's figure
 * can never be computed two different ways.
 *
 * At build time because it is the same answer for everybody and it never
 * changes between deploys. Doing it in the browser would mean shipping 5.9 MB
 * of geometry to render one paragraph.
 *
 * BARANGAYS WITH NO FLOODING ARE KEPT, with zeroes. "The model does not flood
 * this barangay at all" is a real and useful answer, and a lookup that
 * returns undefined for it would have every caller inventing its own way to
 * say so.
 *
 * Run: pnpm -F @davflood/hazard build:profiles
 */

const OUT = fileURLToPath(
  new URL("../src/barangay-profiles.ts", import.meta.url),
);

/** Three decimals is ~1000 m² — finer than the source data deserves. */
function round(n: number): number {
  return Math.round(n * 1000) / 1000;
}

type Stat = {
  low: number;
  medium: number;
  high: number;
  total: number;
  zones: number;
};

const empty = (): Stat => ({ low: 0, medium: 0, high: 0, total: 0, zones: 0 });

const profiles = new Map<string, Record<number, Stat>>();
for (const b of barangays) {
  profiles.set(b.name, {});
}

for (const scenario of scenarios) {
  const path = fileURLToPath(
    new URL(`../src/data/davao-${scenario.years}.json`, import.meta.url),
  );
  const fc: HazardCollection = JSON.parse(readFileSync(path, "utf8"));

  /* Split first, measure second. footprintOf takes a collection, so each
     barangay is handed its own — which keeps the measurement identical to the
     city-wide one rather than a reimplementation that drifts. */
  const byBarangay = new Map<string, HazardCollection["features"]>();
  for (const feature of fc.features) {
    const name = feature.properties?.barangay;
    if (!name) continue;
    const bucket = byBarangay.get(name);
    if (bucket) bucket.push(feature);
    else byBarangay.set(name, [feature]);
  }

  for (const [name, features] of byBarangay) {
    const entry = profiles.get(name);
    if (!entry) {
      console.warn(`  ! hazard tagged "${name}", which is not in barangays.ts`);
      continue;
    }
    const fp = footprintOf({ type: "FeatureCollection", features });
    entry[scenario.years] = {
      low: round(fp.km2.low),
      medium: round(fp.km2.medium),
      high: round(fp.km2.high),
      total: round(fp.totalKm2),
      zones: fp.zones,
    };
  }

  const flooded = [...byBarangay.keys()].length;
  console.log(`  ${scenario.label}: ${fc.features.length} zones across ${flooded} barangays`);
}

const rows = [...profiles.entries()]
  .map(([name, byScenario]) => {
    const cells = scenarios
      .map((s) => {
        const stat = byScenario[s.years] ?? empty();
        return `${s.years}: { low: ${stat.low}, medium: ${stat.medium}, high: ${stat.high}, total: ${stat.total}, zones: ${stat.zones} }`;
      })
      .join(", ");
    return `\t${JSON.stringify(name)}: { ${cells} },`;
  })
  .join("\n");

const file = `import type { ScenarioYears } from "./scenarios";

/**
 * How much of each barangay the model floods, by scenario.
 *
 * GENERATED by scripts/build-barangay-profiles.ts — do not edit by hand.
 * Regenerate with: pnpm --filter @davflood/hazard build:profiles
 *
 * Areas are square kilometres of MODELLED FLOOD FOOTPRINT, not a share of the
 * barangay: OpenStreetMap gives Davao's barangays as centroids rather than
 * boundaries for two thirds of them, so there is no denominator to divide by.
 * A figure in km² is honest; a percentage would be invented.
 *
 * All zeroes means the model does not flood that barangay in that scenario.
 * That is an answer, not missing data.
 */

export type BarangayStat = {
\t/** km² in each depth band */
\tlow: number;
\tmedium: number;
\thigh: number;
\t/** km² flooded in total */
\ttotal: number;
\t/** how many polygons make it up */
\tzones: number;
};

export const BARANGAY_PROFILES: Record<
\tstring,
\tRecord<ScenarioYears, BarangayStat>
> = {
${rows}
};
`;

writeFileSync(OUT, file);
console.log(`barangay-profiles.ts — ${profiles.size} barangays`);
