/**
 * Davao City's barangays.
 *
 * GENERATED by scripts/build-admin-data.ts from OpenStreetMap — do not edit by
 * hand. Regenerate with: pnpm --filter @davflood/hazard build:admin
 *
 * 183 barangays, against the city's 182 official ones. Every entry is
 * tagged admin_level=10 in OSM, which is what distinguishes a barangay from the
 * districts and sitios mapped at a similar size (Bajada, Lanang, Matina and
 * Obrero are Davao districts, not barangays, and are deliberately absent).
 *
 * `surveyed` says how good the centroid is: 117 come from a boundary
 * relation and are derived from surveyed geometry, while 66 exist in OSM only
 * as a single mapped point and are approximate. Both are real barangays — the
 * northern coastal ones (Panacan, Ilang, Tibungco, Bunawan, Lasang) are all
 * point-only, and excluding them made the map look like those places never
 * flood.
 *
 * The count runs 1 over the official 182. Reconciling exactly would need the
 * PSA barangay register, which is not available offline; the difference is
 * small enough to leave visible rather than paper over.
 *
 * Hazard geometry is clipped to the city outline rather than assembled per
 * barangay, so the map covers the whole city regardless of this list.
 */

export type Barangay = {
	name: string;
	/** the numbered downtown barangays of the Poblacion district */
	poblacion?: boolean;
	center: [number, number];
	/** true when the centroid comes from a surveyed boundary, not a point */
	surveyed: boolean;
};

/** How many barangays this list actually carries. */
export const BARANGAYS_MAPPED = 183;
/** How many the city officially has, per the PSA barangay register. */
export const BARANGAYS_OFFICIAL = 182;
/** How many have a surveyed boundary behind their centroid. */
export const BARANGAYS_SURVEYED = 117;

export const barangays: Barangay[] = [
	{ name: "1-A Bolton Riverside", poblacion: true, center: [125.60654, 7.06154], surveyed: true },
	{ name: "19-B Garcia Heights", poblacion: true, center: [125.60331, 7.09233], surveyed: true },
	{ name: "23-C Darussalam", poblacion: true, center: [125.62409, 7.07138], surveyed: true },
	{ name: "24-C Fatima", poblacion: true, center: [125.61706, 7.06927], surveyed: true },
	{ name: "26-C Silangan", poblacion: true, center: [125.62285, 7.07266], surveyed: true },
	{ name: "27-C Santa Ana", poblacion: true, center: [125.62319, 7.0754], surveyed: true },
	{ name: "31-D Roxas", poblacion: true, center: [125.61674, 7.06402], surveyed: true },
	{ name: "33-D Bagoroma", poblacion: true, center: [125.61477, 7.06791], surveyed: true },
	{ name: "5-A Bankerohan", poblacion: true, center: [125.59846, 7.06948], surveyed: true },
	{ name: "6-A Saint Jude", poblacion: true, center: [125.60254, 7.07064], surveyed: true },
	{ name: "7-A General Malvar", poblacion: true, center: [125.60475, 7.07279], surveyed: true },
	{ name: "74-A Matina Crossing", poblacion: true, center: [125.57854, 7.06049], surveyed: true },
	{ name: "75-A Matina Aplaya", poblacion: true, center: [125.57502, 7.03963], surveyed: true },
	{ name: "76-A Bucana", poblacion: true, center: [125.59976, 7.05357], surveyed: true },
	{ name: "Acacia", center: [125.6025, 7.19209], surveyed: false },
	{ name: "Agdao Proper", center: [125.62399, 7.08464], surveyed: true },
	{ name: "Alambre", center: [125.47123, 7.06041], surveyed: false },
	{ name: "Alfonso Angliongto Sr.", center: [125.63538, 7.11003], surveyed: false },
	{ name: "Angalan", center: [125.46363, 7.11875], surveyed: false },
	{ name: "Atan-Awe", center: [125.40651, 6.97433], surveyed: false },
	{ name: "Baganihan", center: [125.25425, 7.45988], surveyed: true },
	{ name: "Bago Aplaya", center: [125.53308, 7.0426], surveyed: true },
	{ name: "Bago Gallera", center: [125.51793, 7.05393], surveyed: true },
	{ name: "Bago Oshiro", center: [125.49639, 7.07744], surveyed: false },
	{ name: "Baguio Proper", center: [125.39621, 7.16958], surveyed: true },
	{ name: "Balingaeng", center: [125.46584, 7.13355], surveyed: false },
	{ name: "Baliok", center: [125.50226, 7.04673], surveyed: true },
	{ name: "Bankas Heights", center: [125.48962, 7.0576], surveyed: false },
	{ name: "Bantol", center: [125.3417, 7.30166], surveyed: true },
	{ name: "Baracatan", center: [125.42761, 6.97181], surveyed: false },
	{ name: "Barangay 10-A", poblacion: true, center: [125.6027, 7.08094], surveyed: true },
	{ name: "Barangay 11-B", poblacion: true, center: [125.60988, 7.07789], surveyed: true },
	{ name: "Barangay 12-B", poblacion: true, center: [125.61128, 7.07969], surveyed: true },
	{ name: "Barangay 13-B", poblacion: true, center: [125.61385, 7.07981], surveyed: true },
	{ name: "Barangay 14-B", poblacion: true, center: [125.61679, 7.07949], surveyed: true },
	{ name: "Barangay 15-B", poblacion: true, center: [125.61905, 7.08094], surveyed: true },
	{ name: "Barangay 16-B", poblacion: true, center: [125.61697, 7.08343], surveyed: true },
	{ name: "Barangay 17-B", poblacion: true, center: [125.61637, 7.08416], surveyed: true },
	{ name: "Barangay 18-B", poblacion: true, center: [125.61482, 7.08552], surveyed: true },
	{ name: "Barangay 2-A", poblacion: true, center: [125.60529, 7.0663], surveyed: true },
	{ name: "Barangay 20-B", poblacion: true, center: [125.61399, 7.09], surveyed: true },
	{ name: "Barangay 21-C", poblacion: true, center: [125.61995, 7.06692], surveyed: true },
	{ name: "Barangay 22-C", poblacion: true, center: [125.6214, 7.06919], surveyed: true },
	{ name: "Barangay 25-C", poblacion: true, center: [125.61936, 7.06984], surveyed: true },
	{ name: "Barangay 28-C", poblacion: true, center: [125.61871, 7.0725], surveyed: true },
	{ name: "Barangay 29-C", poblacion: true, center: [125.61482, 7.0723], surveyed: true },
	{ name: "Barangay 3-A", poblacion: true, center: [125.60686, 7.06779], surveyed: true },
	{ name: "Barangay 30-C", poblacion: true, center: [125.61502, 7.07524], surveyed: true },
	{ name: "Barangay 32-D", poblacion: true, center: [125.61436, 7.07109], surveyed: true },
	{ name: "Barangay 34-D", poblacion: true, center: [125.61173, 7.07018], surveyed: true },
	{ name: "Barangay 35-D", poblacion: true, center: [125.6113, 7.06648], surveyed: true },
	{ name: "Barangay 36-D", poblacion: true, center: [125.61378, 7.06536], surveyed: true },
	{ name: "Barangay 37-D", poblacion: true, center: [125.61398, 7.06406], surveyed: true },
	{ name: "Barangay 38-D", poblacion: true, center: [125.61093, 7.06458], surveyed: true },
	{ name: "Barangay 39-D", poblacion: true, center: [125.61036, 7.06225], surveyed: true },
	{ name: "Barangay 4-A", poblacion: true, center: [125.60856, 7.07174], surveyed: true },
	{ name: "Barangay 40-D", poblacion: true, center: [125.6088, 7.0602], surveyed: true },
	{ name: "Barangay 8-A", poblacion: true, center: [125.59614, 7.07664], surveyed: true },
	{ name: "Barangay 9-A", poblacion: true, center: [125.60032, 7.08092], surveyed: true },
	{ name: "Bato", center: [125.47882, 7.03124], surveyed: false },
	{ name: "Bayabas", center: [125.4388, 7.02492], surveyed: false },
	{ name: "Biao Escuela", center: [125.52161, 7.16385], surveyed: false },
	{ name: "Biao Guianga", center: [125.49777, 7.14877], surveyed: false },
	{ name: "Biao Joaquin", center: [125.494, 7.18355], surveyed: true },
	{ name: "Binugao", center: [125.47802, 6.976], surveyed: false },
	{ name: "Buda", center: [125.23889, 7.51722], surveyed: true },
	{ name: "Bugac", center: [125.64901, 7.1839], surveyed: false },
	{ name: "Buhangin", center: [125.6135, 7.1087], surveyed: false },
	{ name: "Bunawan", center: [125.64242, 7.2358], surveyed: false },
	{ name: "Cabantian", center: [125.61948, 7.12791], surveyed: false },
	{ name: "Cadalian", center: [125.37603, 7.14857], surveyed: true },
	{ name: "Calinan Poblacion", center: [125.4558, 7.1908], surveyed: true },
	{ name: "Callawa", center: [125.54503, 7.21042], surveyed: false },
	{ name: "Camansi", center: [125.43797, 7.08671], surveyed: false },
	{ name: "Carmen", center: [125.34613, 7.11657], surveyed: true },
	{ name: "Catalunan Grande", center: [125.52945, 7.08628], surveyed: true },
	{ name: "Catalunan Pequeño", center: [125.52286, 7.07526], surveyed: true },
	{ name: "Catigan", center: [125.42743, 7.00092], surveyed: false },
	{ name: "Cawayan", center: [125.41088, 7.15183], surveyed: true },
	{ name: "Centro", center: [125.63844, 7.09145], surveyed: true },
	{ name: "Colosas", center: [125.51284, 7.49907], surveyed: true },
	{ name: "Communal", center: [125.62262, 7.1413], surveyed: false },
	{ name: "Crossing Bayabas", center: [125.49482, 7.02296], surveyed: false },
	{ name: "Dacudao", center: [125.47963, 7.22378], surveyed: true },
	{ name: "Dalag Lumot", center: [125.24867, 7.25366], surveyed: true },
	{ name: "Dalagdag", center: [125.50668, 7.24811], surveyed: true },
	{ name: "Daliao", center: [125.5041, 7.009], surveyed: false },
	{ name: "Daliaon Plantation", center: [125.41418, 7.08349], surveyed: false },
	{ name: "Datu Salumay", center: [125.26478, 7.49326], surveyed: true },
	{ name: "Dominga", center: [125.48868, 7.25579], surveyed: true },
	{ name: "Dumoy", center: [125.51347, 7.02944], surveyed: true },
	{ name: "Eden", center: [125.39781, 7.03189], surveyed: false },
	{ name: "Fatima", center: [125.52466, 7.28899], surveyed: true },
	{ name: "Gatungan", center: [125.59682, 7.21432], surveyed: false },
	{ name: "Gumalang", center: [125.40142, 7.22102], surveyed: true },
	{ name: "Gumitan", center: [125.36018, 7.4328], surveyed: true },
	{ name: "Ilang", center: [125.65203, 7.18067], surveyed: false },
	{ name: "Inayangan", center: [125.44405, 7.27523], surveyed: true },
	{ name: "Indangan", center: [125.59463, 7.16729], surveyed: false },
	{ name: "Kapitan Tomas Monteverde Sr.", center: [125.62209, 7.07962], surveyed: true },
	{ name: "Kilate", center: [125.43923, 7.05095], surveyed: false },
	{ name: "Lacson", center: [125.43674, 7.21795], surveyed: true },
	{ name: "Lamanan", center: [125.43604, 7.28763], surveyed: true },
	{ name: "Lampiano", center: [125.5191, 7.21694], surveyed: true },
	{ name: "Langub", center: [125.56048, 7.1068], surveyed: true },
	{ name: "Lapu-Lapu", center: [125.64341, 7.09793], surveyed: true },
	{ name: "Lasang", center: [125.66501, 7.26709], surveyed: false },
	{ name: "Leon Garcia Sr.", center: [125.62735, 7.08162], surveyed: true },
	{ name: "Lizada", center: [125.48889, 7.01124], surveyed: false },
	{ name: "Los Amigos", center: [125.47961, 7.14127], surveyed: false },
	{ name: "Lubogan", center: [125.49419, 7.03325], surveyed: false },
	{ name: "Lumiad", center: [125.46098, 7.39002], surveyed: true },
	{ name: "Ma-a", center: [125.58674, 7.0832], surveyed: true },
	{ name: "Mabuhay", center: [125.53153, 7.33235], surveyed: true },
	{ name: "Magsaysay", center: [125.27795, 7.30845], surveyed: true },
	{ name: "Magtuod", center: [125.56806, 7.12184], surveyed: true },
	{ name: "Mahayag", center: [125.6194, 7.2188], surveyed: false },
	{ name: "Malabog", center: [125.4392, 7.36996], surveyed: true },
	{ name: "Malagos", center: [125.4255, 7.18483], surveyed: true },
	{ name: "Malamba", center: [125.33361, 7.40561], surveyed: true },
	{ name: "Manambulan", center: [125.45347, 7.10282], surveyed: false },
	{ name: "Mandug", center: [125.57676, 7.16506], surveyed: false },
	{ name: "Manuel Guianga", center: [125.41332, 7.10458], surveyed: false },
	{ name: "Mapula", center: [125.4401, 7.44699], surveyed: true },
	{ name: "Marapangi", center: [125.48723, 7.01594], surveyed: false },
	{ name: "Marilog Proper", center: [125.29147, 7.37518], surveyed: true },
	{ name: "Matina Biao", center: [125.53982, 7.13876], surveyed: false },
	{ name: "Matina Pangi", center: [125.56649, 7.07881], surveyed: true },
	{ name: "Megkawayan", center: [125.43715, 7.31258], surveyed: true },
	{ name: "Mintal", center: [125.50188, 7.0924], surveyed: false },
	{ name: "Mudiang", center: [125.62235, 7.18314], surveyed: false },
	{ name: "Mulig", center: [125.45951, 7.08192], surveyed: false },
	{ name: "New Carmen", center: [125.55936, 7.14653], surveyed: false },
	{ name: "New Valencia", center: [125.53754, 7.1719], surveyed: false },
	{ name: "Paciano Bangoy", center: [125.61957, 7.09065], surveyed: true },
	{ name: "Pampanga", center: [125.64868, 7.11906], surveyed: false },
	{ name: "Panacan", center: [125.65866, 7.15148], surveyed: false },
	{ name: "Pañalum", center: [125.49973, 7.34519], surveyed: true },
	{ name: "Pandaitan", center: [125.51639, 7.40498], surveyed: true },
	{ name: "Pangyan", center: [125.50404, 7.20878], surveyed: true },
	{ name: "Paquibato Proper", center: [125.48438, 7.38193], surveyed: true },
	{ name: "Paradise Embac", center: [125.5237, 7.36188], surveyed: true },
	{ name: "Rafael Castillo", center: [125.63757, 7.09895], surveyed: true },
	{ name: "Riverside", center: [125.47313, 7.16602], surveyed: true },
	{ name: "Salapawan", center: [125.47158, 7.46137], surveyed: true },
	{ name: "Salaysay", center: [125.26531, 7.226], surveyed: true },
	{ name: "Saloy", center: [125.41124, 7.28883], surveyed: true },
	{ name: "San Antonio", center: [125.63087, 7.09482], surveyed: true },
	{ name: "San Isidro", center: [125.63655, 7.25869], surveyed: false },
	{ name: "Santo Niño", center: [125.50823, 7.08557], surveyed: false },
	{ name: "Sasa", center: [125.66123, 7.1248], surveyed: false },
	{ name: "Sibulan", center: [125.39177, 6.98063], surveyed: false },
	{ name: "Sirawan", center: [125.48198, 6.9905], surveyed: false },
	{ name: "Sirib", center: [125.38865, 7.11574], surveyed: true },
	{ name: "Suawan", center: [125.33619, 7.23944], surveyed: true },
	{ name: "Subasta", center: [125.43948, 7.14193], surveyed: true },
	{ name: "Sumimao", center: [125.48032, 7.2942], surveyed: true },
	{ name: "Tacunan", center: [125.51694, 7.11364], surveyed: false },
	{ name: "Tagakpan", center: [125.43137, 7.12587], surveyed: false },
	{ name: "Tagluno", center: [125.44128, 7.06792], surveyed: false },
	{ name: "Tagurano", center: [125.41426, 7.04634], surveyed: false },
	{ name: "Talandang", center: [125.51794, 7.184], surveyed: false },
	{ name: "Talomo Proper", center: [125.55065, 7.05616], surveyed: true },
	{ name: "Talomo River", center: [125.47859, 7.19116], surveyed: true },
	{ name: "Tamayong", center: [125.35932, 7.11018], surveyed: true },
	{ name: "Tambobong", center: [125.31778, 7.18926], surveyed: true },
	{ name: "Tamugan", center: [125.37335, 7.29282], surveyed: true },
	{ name: "Tapak", center: [125.40848, 7.54829], surveyed: true },
	{ name: "Tawan-Tawan", center: [125.34696, 7.15375], surveyed: true },
	{ name: "Tibuloy", center: [125.43752, 6.98294], surveyed: false },
	{ name: "Tibungco", center: [125.6488, 7.1905], surveyed: false },
	{ name: "Tigatto", center: [125.59865, 7.11953], surveyed: false },
	{ name: "Toril", center: [125.49744, 7.01875], surveyed: false },
	{ name: "Tugbok", center: [125.48412, 7.10994], surveyed: false },
	{ name: "Tungkalan", center: [125.42483, 7.07469], surveyed: false },
	{ name: "Ubalde", center: [125.63513, 7.09473], surveyed: true },
	{ name: "Ula", center: [125.49277, 7.13192], surveyed: false },
	{ name: "Vicente Duterte", center: [125.63216, 7.08823], surveyed: true },
	{ name: "Vicente Hizon Sr.", center: [125.64962, 7.11108], surveyed: false },
	{ name: "Waan", center: [125.57644, 7.12827], surveyed: false },
	{ name: "Wangan", center: [125.44579, 7.16912], surveyed: true },
	{ name: "Wilfredo C. Aquino", center: [125.62448, 7.0936], surveyed: true },
	{ name: "Wines", center: [125.38722, 7.19961], surveyed: true },
];

export function normalizeName(value: string): string {
	return value
		.normalize("NFD")
		.replace(/[\u0300-\u036f]/g, "")
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, " ")
		.trim();
}

export function searchBarangays(query: string, limit = 200): Barangay[] {
	const q = normalizeName(query);
	if (!q) return barangays.slice(0, limit);

	const scored = barangays
		.map((b) => {
			const n = normalizeName(b.name);
			// prefix match beats substring match beats nothing
			const score = n.startsWith(q) ? 2 : n.includes(q) ? 1 : 0;
			return { b, score };
		})
		.filter((x) => x.score > 0)
		.sort((a, z) => z.score - a.score || a.b.name.localeCompare(z.b.name));

	return scored.slice(0, limit).map((x) => x.b);
}
